DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS mixer;

CREATE TABLE IF NOT EXISTS students(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  secondName VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  groupNumber INTEGER,
  score INTEGER --по умолчанию ноль?
);

CREATE TABLE IF NOT EXISTS events(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  nameEvent VARCHAR(255) NOT NULL,
  volonteerRoles VARCHAR(255) NOT NULL,
  dateEvent VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS mixer(
  idEvent INTEGER,
  idStudent INTEGER,
  studentRole VARCHAR(255),
  scoreForEvent INTEGER
);

